<a href="https://colab.research.google.com/github/subham-28/DL-Notebooks/blob/main/integer_encoding_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega indian jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inquillab zindabad']

In [20]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [21]:
tokenizer.fit_on_texts(docs)

In [22]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'indian': 13,
 'bharat': 14,
 'mata': 15,
 'modi': 16,
 'ji': 17,
 'inquillab': 18,
 'zindabad': 19}

In [23]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 3),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('indian', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquillab', 1),
             ('zindabad', 1)])

In [24]:
tokenizer.document_count

10

In [25]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 13, 3],
 [14, 15, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [16, 17, 5, 6],
 [18, 19]]

In [26]:
from keras.utils import pad_sequences

In [27]:
sequences = pad_sequences(sequences,padding='post')

In [28]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3, 13,  3],
       [14, 15,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [16, 17,  5,  6,  0],
       [18, 19,  0,  0,  0]], dtype=int32)

In [29]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.compile('adam','accuracy')

In [31]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step
[[[-4.1783523e-02 -9.2355832e-03]
  [ 4.9555525e-03 -4.7213018e-02]
  [ 4.5842752e-03 -2.6484801e-02]
  [ 4.5842752e-03 -2.6484801e-02]
  [ 4.5842752e-03 -2.6484801e-02]]

 [[ 4.9555525e-03 -4.7213018e-02]
  [ 4.9555525e-03 -4.7213018e-02]
  [ 4.5842752e-03 -2.6484801e-02]
  [ 4.5842752e-03 -2.6484801e-02]
  [ 4.5842752e-03 -2.6484801e-02]]

 [[-1.6499937e-02 -7.3216669e-03]
  [-1.6499937e-02 -7.3216669e-03]
  [-9.1362745e-05  3.0127380e-02]
  [ 4.5842752e-03 -2.6484801e-02]
  [ 4.5842752e-03 -2.6484801e-02]]

 [[-3.1758502e-02  4.2678956e-02]
  [-1.9667650e-02 -4.2699203e-03]
  [-3.1758502e-02  4.2678956e-02]
  [-2.8398646e-02 -2.5355363e-02]
  [-3.1758502e-02  4.2678956e-02]]

 [[-2.1728301e-02 -2.6391566e-02]
  [-5.8458559e-03  4.1923095e-02]
  [ 8.1631429e-03 -4.0167347e-03]
  [-1.9962415e-03 -3.2871068e-02]
  [ 4.5842752e-03 -2.6484801e-02]]

 [[-4.5659553e-02  2.7969528e-02]
  [-4.5659553e-02  2.7969528e-02]
  [ 4.5842752e-03 -2.6484801e-02]

## Testing on IMDB dataset

In [11]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [12]:
(x_train,y_train),(x_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [13]:
x_train.shape

(25000,)

In [14]:
x_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [15]:
x_train = pad_sequences(x_train,padding='post')
x_test = pad_sequences(x_test,padding='post')

In [16]:
x_train.shape

(25000, 2494)

In [17]:
model=Sequential()

model.add(SimpleRNN(32,input_shape=(2494,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 115s 145ms/step - accuracy: 0.5093 - loss: 0.6957 - val_accuracy: 0.5042 - val_loss: 0.6937
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 107s 136ms/step - accuracy: 0.4881 - loss: 0.6946 - val_accuracy: 0.5041 - val_loss: 0.6934
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 143s 137ms/step - accuracy: 0.5014 - loss: 0.6939 - val_accuracy: 0.4992 - val_loss: 0.6940
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 114s 146ms/step - accuracy: 0.4945 - loss: 0.6939 - val_accuracy: 0.5046 - val_loss: 0.6936
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 112s 143ms/step - accuracy: 0.5008 - loss: 0.6940 - val_accuracy: 0.5000 - val_loss: 0.6933
